field.field_settings.select_color:
  type: mapping
  label: 'Select color field settings'

field.value.select_color:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Color code'
