entity.color_settings.canonical:
  route_name: dg_color_settings.color_choose_config_form
  base_route: dg_color_settings.color_choose_config_form
  title: 'List'
dg_color_settings.color_config_form:
  route_name: dg_color_settings.color_config_form
  base_route: dg_color_settings.color_choose_config_form
  title: 'Guideline'
entity.color_settings.box_settings:
  route_name: dg_color_settings.box_colors
  base_route: dg_color_settings.color_choose_config_form
  title: 'Ckeditor boxes'
dg_color_settings.alert_color_config_form:
  route_name: dg_color_settings.alert_color_choose_config_form
  base_route: dg_color_settings.color_choose_config_form
  title: 'Aert notification'
