<?php

/**
 * @file
 * Contains dg_color_settings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Field\FieldItemList;

/**
 * Implements hook_help().
 */
function dg_color_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the allowed_languages module.
    case 'help.page.dg_color_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dg Guideline settings and configuration pages.') . '</p>';
      return $output;
  }
}

function dg_color_get_color($color_type = NULL, $domian = NULL) {
  $config = \Drupal::config('dg_color_settings.color_settings');
  if (!$domian) {
    $loader = \Drupal::service('guideline.negotiator');
    $domian = $loader->getActiveGuideline();
  }
  $color_config = $config->get($domian->id());
  if (!is_array($color_config)) {
    return NULL;
  }

  if ($color_type && isset($color_config[$color_type])) {
    return $color_config[$color_type];
  } else {
    return $color_config;
  }
}

/**
 * Implements hook_page_attachments().
 */
function dg_color_settings_page_attachments(array &$page) {
  $config = \Drupal::config('dg_color_settings.box_color');
  $page['#attached']['drupalSettings']['MSF']["colors"] = [
      "box1" => $config->get("box1_color"),
      "box2" => $config->get("box2_color"),
      "box3" => $config->get("box3_color"),
  ];

  $colorOptions = \Drupal::config('dg_color_settings.color_options');
  $colorOptions = $colorOptions->get("global");
  if($colorOptions) {
    foreach ($colorOptions as $key => $colorName) {
      $page['#attached']['drupalSettings']['MSF']["guideline_color_set"][$key] = [
        "color1" => $colorName['color1'],
        "color2" => $colorName['color2'],
      ];
    }
  }
  $colorOptions = \Drupal::config('dg_color_settings.alter_color_options ');
  $colorOptions = $colorOptions->get("global");
  if($colorOptions) {
    foreach ($colorOptions as $key => $colorName) {
      $page['#attached']['drupalSettings']['MSF']["alert_color_set"][$key] = [
        "text_color" => $colorName['text_color'],
        "background_color" => $colorName['background_color'],
      ];
    }
  }
}
