dg_color_settings.color_config_form:
  path: '/admin/config/dg/color-config'
  defaults:
    _form: '\Drupal\dg_color_settings\Form\GuidelineColorSettingsForm'
    _title: 'Guideline color settings'
  requirements:
    _permission: 'access guideline color settings'
  options:
    _admin_route: TRUE

dg_color_settings.color_choose_config_form:
  path: '/admin/config/dg/color-choose-config'
  defaults:
    _form: '\Drupal\dg_color_settings\Form\ColorChooseSettingsForm'
    _title: 'Color list settings'
  requirements:
    _permission: 'access guideline color settings'
  options:
    _admin_route: TRUE

dg_color_settings.alert_color_choose_config_form:
  path: '/admin/config/dg/alert-color-choose-config'
  defaults:
    _form: '\Drupal\dg_color_settings\Form\AlertColorChooseSettingsForm'
    _title: 'Alert Notification Color list settings'
  requirements:
    _permission: 'access toolbar color settings'
  options:
    _admin_route: TRUE

dg_color_settings.box_colors:
  path: '/admin/config/dg/box-color'
  defaults:
    _form: '\Drupal\dg_color_settings\Form\BoxColorSettingsForm'
    _title: 'Ckeditor box color settings'
  requirements:
    _permission: 'access toolbar color settings'
  options:
    _admin_route: TRUE
